'use strict';
window.KBRShift=(()=>{
let shifts=[],events=[],corrections=[],loading=false,saving=false,hasLoaded=false;let countForm=null,countKind='',denomination=1,countText='';const quantities={};const denominations=[1,5,10,20,50,100,500,1000];const queue='kbr_drawer_action_v1';const nameKey='kbr_cashier_username_'+(KBRCloud.session()?.user?.id||'staff');
const money=n=>peso(Number(n)||0),time=t=>new Date(t).toLocaleString('en-PH',{timeZone:'Asia/Manila'});
function active(){return shifts.find(s=>s.status==='open');}
function totals(s){const rows=events.filter(e=>e.shift_id===s.id);return {cash:Number(s.opening_cash)+rows.reduce((n,e)=>n+Number(e.cash),0),gcash:rows.reduce((n,e)=>n+Number(e.gcash),0),cashPayments:rows.filter(e=>e.kind==='payment').reduce((n,e)=>n+Number(e.cash),0),added:rows.filter(e=>e.kind==='cash-in').reduce((n,e)=>n+Number(e.cash),0),out:-rows.filter(e=>e.kind==='cash-out').reduce((n,e)=>n+Number(e.cash),0)};}
async function refresh(prompt=false){if(loading)return;loading=true;try{shifts=await KBRCloud.rows('/rest/v1/kbr_shifts?select=*&order=opened_at.desc&limit=20');events=shifts.length?await KBRCloud.rows('/rest/v1/kbr_shift_events?shift_id=in.('+shifts.map(s=>s.id).join(',')+')&select=*&order=recorded_at.desc'):[];corrections=shifts.length?await KBRCloud.rows('/rest/v1/kbr_drawer_corrections?shift_id=in.('+shifts.map(s=>s.id).join(',')+')&select=*&order=approved_at.desc'):[];hasLoaded=true;render();if(active()&&countKind==='open'&&countForm?.isConnected){KBRSyncUI.close();countForm=null;countKind='';}if(prompt&&!active())action('open');}catch(e){if(baristaView==='shift')document.getElementById('baristaShiftView').innerHTML='<p>Could not load the cash drawer.</p><button onclick="KBRShift.refresh()">Retry</button>';}finally{loading=false;}}
let drawerTab='cash',cashExpanded=false;
function setTab(tab){drawerTab=tab;render();}
function render(){const host=document.getElementById('baristaShiftView');if(!host)return;const s=active(),pending=KBRCloud.read(queue),t=s?totals(s):null;
 host.innerHTML=drawerTab==='cash'?`<h3>Cash Registry</h3>${s?`<button style="width:100%;text-align:left" onclick="KBRShift.toggleCash()"><small>Current cash · expected</small><h2>${money(t.cash)}</h2><small>${cashExpanded?'Hide':'Show'} cash details</small></button>${cashExpanded?`<div class="history-total-strip"><div class="history-total-card">Opening cash<b>${money(s.opening_cash)}</b></div><div class="history-total-card">Cash payments<b>${money(t.cashPayments)}</b></div><div class="history-total-card">Cash in<b>${money(t.added)}</b></div><div class="history-total-card">Cash out<b>${money(t.out)}</b></div><div class="history-total-card">GCash received<b>${money(t.gcash)}</b></div></div>`:''}<div class="barista-actions"><button onclick="KBRShift.action('cash-in')">Cash In</button><button onclick="KBRShift.action('cash-out')">Cash Out</button><button onclick="KBRShift.action('handover')">Cash Handover</button></div>${eventList(s)}`:'<p>Shop is closed. Open it in the Open / End Shift tab to start the cash registry.</p>'}`:`<h3>Open / End Shift</h3>${s?`<p>Opened by ${escapeHtml(s.opened_name)} · ${time(s.opened_at)}</p><p>Opening cash ${money(s.opening_cash)} · Current cash ${money(t.cash)}</p><div class="barista-actions"><button onclick="KBRShift.action('close')">Close Shop</button><button onclick="KBRShift.correctOpening('${s.id}')">Correct Opening Count</button><button onclick="KBRShift.correct('${s.id}',null)">Void Test Shift</button></div>${auditList(s)}`:'<button onclick="KBRShift.action(\'open\')">Open Shop</button>'}<h3>Previous shop records</h3>${shifts.filter(x=>x.status!=='open').map(x=>`<details class="barista-order-card"><summary>${time(x.opened_at)} · ${escapeHtml(x.opened_name)} · ${escapeHtml(x.status)}</summary>${eventList(x)}${auditList(x)}</details>`).join('')}`;

}
function eventList(s){const rows=events.filter(e=>e.shift_id===s.id);return `<details><summary>Drawer activity (${rows.length})</summary>${rows.map(e=>`<p>${time(e.recorded_at)} · ${escapeHtml(e.kind)} · ${escapeHtml(e.staff_name)}${e.cashier_username?' (@'+escapeHtml(e.cashier_username)+')':''}<br>${e.kind==='payment'?`Cash ${money(e.cash)} · GCash ${money(e.gcash)}`:e.kind==='handover'||e.kind==='close'?`Counted ${money(e.counted)} · Expected ${money(e.expected)} · Difference ${money(e.variance)}`:e.kind==='opening'?`Opening ${money(e.counted)}`:money(e.cash)} · ${escapeHtml(e.note||'')}${s.status!=='voided'&&e.kind!=='payment'?`<br><button onclick="KBRShift.correct('${s.id}','${e.operation}')">Correct record</button>`:''}${Object.keys(e.denominations||{}).length?'<br>Count: '+Object.entries(e.denominations).filter(([n,q])=>Number(q)>0).map(([n,q])=>'₱'+n+' × '+q).join(' · '):''}</p>`).join('')}</details>`;}
function auditList(s){const rows=corrections.filter(a=>a.shift_id===s.id);return rows.length?`<details><summary>Manager corrections (${rows.length})</summary>${rows.map(a=>{const old=a.before_record.events?.find(e=>e.operation===a.event_id),next=a.after_record.events?.find(e=>e.operation===a.event_id);return `<section class="barista-order-card"><b>${a.kind==='void'?'Test shift voided':'Corrected '+escapeHtml(old?.kind||'record')}</b><p>${time(a.approved_at)} · ${escapeHtml(a.approved_name)}${a.cashier_username?' (@'+escapeHtml(a.cashier_username)+')':''}<br>Reason: ${escapeHtml(a.reason)}</p>${old?`<p>Original: ${money(old.counted??Math.abs(Number(old.cash)))} → Corrected: ${money(next.counted??Math.abs(Number(next.cash)))}</p><details><summary>Original and corrected denomination counts</summary><p>Original: ${Object.entries(old.denominations||{}).map(([n,q])=>'₱'+n+' × '+q).join(' · ')||'Not recorded'}<br>Corrected: ${Object.entries(next.denominations||{}).map(([n,q])=>'₱'+n+' × '+q).join(' · ')||'Not applicable'}</p></details>`:''}</section>`;}).join('')}</details>`:'';}
function cashierMarkup(username=''){return `<label>Cashier username<input name="cashierUsername" required minlength="3" maxlength="30" autocomplete="off" autocapitalize="none" value="${escapeHtml(username)}"></label><label>Cashier PIN<input name="cashierPin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="off" required><small>Use your 4–6 digit Barista Drink PIN.</small></label>`;}
function cashierArgs(form){return {p_cashier_username:form.elements.cashierUsername.value.trim().toLowerCase(),p_cashier_pin:form.elements.cashierPin.value};}
function correctOpening(id){const event=events.find(e=>e.shift_id===id&&e.kind==='opening');if(event)correct(id,event.operation);}
function correct(shiftId,eventId){if(saving)return;if(KBRCloud.read(queue)){retry();return;}const s=shifts.find(s=>s.id===shiftId),event=events.find(e=>e.operation===eventId),voiding=!eventId;if(!s||s.status==='voided'||(!voiding&&!event))return;const count=event&&['opening','handover','close'].includes(event.kind);
 KBRSyncUI.screen(voiding?'Void Test Shift':'Correct '+event.kind,voiding?'This marks the shift as voided and allows a fresh opening. Orders, payments, customer debt and inventory remain unchanged. Cancel test transactions separately.':'Manager PIN approval required. The original record is retained.',[['Back',()=>KBRSyncUI.close()]]);
 const form=document.createElement('form');if(count)document.querySelector('#cloudScreen .cloud-box').classList.add('drawer-count');form.innerHTML=`${cashierMarkup(localStorage.getItem(nameKey)||'')}${voiding?'':`<label>Corrected ${count?'cash counted':'amount (zero reverses a mistaken entry)'}<input name="amount" type="number" min="0" step="0.01" value="${Number(event.counted??Math.abs(Number(event.cash)))||0}" ${count?'readonly':''} required></label>${count?countMarkup():''}`}<label>Reason<textarea name="reason" minlength="3" maxlength="500" required></textarea></label><label>Manager PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="off" required></label><button type="submit">${voiding?'Approve void test shift':'Approve correction'}</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);
 if(count){countForm=form;countKind='correction';for(const n of denominations)quantities[n]=Number(event.denominations?.[n])||0;denomination=denominations.find(n=>quantities[n]>0)||1;countText='';updateCount();}
 form.onsubmit=async e=>{e.preventDefault();const args={_rpcName:'kbr_cashier_correct_drawer',p_shift:shiftId,p_event:eventId,p_revision:event?.revision||null,p_kind:voiding?'void':'correct',p_amount:voiding?0:Number(form.elements.amount.value),p_denominations:count?{...quantities}:{},p_reason:form.elements.reason.value,p_staff:'',...cashierArgs(form),p_pin:form.elements.pin.value,p_operation:KBRCloud.uuid()};form.elements.pin.value='';form.elements.cashierPin.value='';await save(args);};
}
function countMarkup(){return `<div class="count-layout"><div class="denomination-grid">${denominations.map(n=>`<button type="button" id="denom${n}" onclick="KBRShift.selectDenom(${n})">₱${n}<br><span id="denomQty${n}">0 pieces</span></button>`).join('')}</div><div class="count-controls"><p id="selectedDenomination"></p><label>Number of pieces<input id="denomQuantity" type="text" inputmode="numeric" value="0" readonly></label><div class="count-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" onclick="KBRShift.countKey('${n}')">${n}</button>`).join('')}<button type="button" onclick="KBRShift.countKey('clear')">Clear</button><button type="button" onclick="KBRShift.countKey('0')">0</button><button type="button" onclick="KBRShift.countKey('back')" aria-label="Delete last digit">⌫</button></div></div></div>`;}
function selectDenom(n){if(!denominations.includes(n))return;denomination=n;countText='';updateCount();}
function countKey(key){if(!countForm)return;if(key==='clear')countText='0';else if(key==='back')countText=(countText||String(quantities[denomination]||0)).slice(0,-1)||'0';else if(/^\d$/.test(key))countText=(countText+key).replace(/^0+(?=\d)/,'');else return;if(countText.length>7||Number(countText)>1000000){countText=String(quantities[denomination]||0);return;}quantities[denomination]=Number(countText)||0;updateCount();}
function updateCount(){if(!countForm)return;for(const n of denominations){document.getElementById('denomQty'+n).textContent=quantities[n]+' pieces · '+money(n*quantities[n]);document.getElementById('denom'+n).classList.toggle('selected',n===denomination);}document.getElementById('selectedDenomination').textContent='Selected: ₱'+denomination+' · enter number of pieces';document.getElementById('denomQuantity').value=quantities[denomination];countForm.elements.amount.value=denominations.reduce((sum,n)=>sum+n*quantities[n],0);countForm.oninput?.();}
function action(kind){if(saving)return;if(KBRCloud.read(queue)){retry();return;}const s=active();if(kind==='open'&&s){KBRSyncUI.close();render();return;}if(kind!=='open'&&!s){refresh(true);return;}const labels={open:'Open Shop Shift','cash-in':'Cash In — add change / money','cash-out':'Cash Out — supplies / refund',handover:'Cash Handover',close:'End Shop Shift'},count=['open','handover','close'].includes(kind),t=s?totals(s):null;
 KBRSyncUI.screen(labels[kind],count?'Count the actual cash in the drawer.':'Record the amount and purpose.',[['Back',()=>KBRSyncUI.close()]]);
 const form=document.createElement('form');if(count)document.querySelector('#cloudScreen .cloud-box').classList.add('drawer-count');form.innerHTML=`${cashierMarkup(localStorage.getItem(nameKey)||'')}<label>${count?'Total cash counted':'Amount'}<input name="amount" type="number" min="${count?0:0.01}" step="0.01" ${count?'readonly value="0"':''} required></label>${count?countMarkup():''}<label>${kind==='handover'?'Handover to / note':'Purpose / note'}<textarea name="note" maxlength="500" ${!count?'required minlength="3"':''}></textarea></label>${t&&count?`<p>Expected drawer cash: ${money(t.cash)}</p><p id="drawerVariance"></p>`:''}${kind==='close'?'<label>Manager PIN (required for a shortage or excess)<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="off"></label>':''}<button type="submit">Save ${labels[kind]}</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);
 if(count){countForm=form;countKind=kind;for(const n of denominations)quantities[n]=0;denomination=1;countText='';updateCount();}
 form.oninput=()=>{const el=document.getElementById('drawerVariance');if(el)el.textContent='Difference: '+money(Number(form.elements.amount.value)-t.cash);};
 form.onsubmit=async e=>{e.preventDefault();const args={p_kind:kind,p_amount:Number(form.elements.amount.value),p_note:form.elements.note.value,p_staff:'',...cashierArgs(form),p_operation:KBRCloud.uuid(),p_shift:s?.id||null,p_pin:form.elements.pin?.value||'',p_denominations:count?{...quantities}:{}};localStorage.setItem(nameKey,args.p_cashier_username);if(form.elements.pin)form.elements.pin.value='';form.elements.cashierPin.value='';await save(args);};
}
async function save(args){if(saving)return;saving=true;const safe={...args,p_pin:'',p_cashier_pin:''};localStorage.setItem(queue,JSON.stringify(safe));KBRSyncUI.screen('Saving drawer change…','Please wait for confirmation.');try{const {_rpcName,...payload}=args;const result=await KBRCloud.rpc(_rpcName||'kbr_cashier_drawer_action',payload);if(result.error){localStorage.removeItem(queue);throw Object.assign(Error(result.error),{definite:true});}localStorage.removeItem(queue);await refresh();KBRSyncUI.close();if(args.p_kind==='handover')KBRSyncUI.screen('Cash handover recorded','The shop shift remains open for the next barista.',[['Sign out',()=>KBRCloud.logout()],['Continue',()=>KBRSyncUI.close()]]);}catch(e){if(e.definite||e.status===400)localStorage.removeItem(queue);KBRSyncUI.screen('Drawer change not confirmed',e.message,[['Review drawer',()=>{KBRSyncUI.close();refresh();}]]);}finally{saving=false;}}
function retry(){const args=KBRCloud.read(queue);if(!args)return;args.p_pin='';args.p_cashier_pin='';if(args._rpcName==='kbr_correct_drawer')args._rpcName='kbr_cashier_correct_drawer';KBRSyncUI.screen('Retry saved drawer change','Enter the original cashier username and PIN. For corrections or a closing difference, enter the manager PIN too. The same operation ID is reused.',[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML=cashierMarkup(args.p_cashier_username||'')+'<label>Manager PIN (if needed)<input name="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off"></label><button type="submit">Retry saved change</button>';document.querySelector('#cloudScreen .cloud-box').append(form);form.onsubmit=e=>{e.preventDefault();Object.assign(args,cashierArgs(form));args.p_pin=form.elements.pin.value;form.elements.pin.value='';form.elements.cashierPin.value='';save(args);};}
return {snapshot(){const s=active();return {loaded:hasLoaded,shift:s?{...s}:null,totals:s?totals(s):null};},setTab,toggleCash(){cashExpanded=!cashExpanded;render();},refresh,render,action,retry,selectDenom,countKey,correct,correctOpening};})();
