(()=>{'use strict';
const host=document.getElementById('workerClockView'),status=document.getElementById('clockStatus');
let workers=[],attendance=[],selected=KBRCloud.read('kbr_clock_profile_v1',{})?.username||'',mode='in',busy=false,refreshing=false,last='';
const worker=()=>workers.find(w=>w.username===selected);
const active=()=>attendance.find(a=>a.barista_id===worker()?.id&&!a.clocked_out_at);
function timer(){const record=active(),el=document.getElementById('workerElapsed');if(!record||!el)return;const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(record.clocked_in_at))/1000));el.textContent=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':');}
function render(){const a=active(),w=worker();if(!a)mode='in';if(a&&mode!=='out'){
 host.innerHTML=`<div class="clock-panes"><section class="barista-order-card"><h2>${escapeHtml(w.name)}</h2><p>@${escapeHtml(w.username)}</p><p>${escapeHtml(w.position||'Barista')}</p><p>Clocked in · free-drink eligibility is automatic.</p><button id="chooseWorker">Choose another worker</button></section><section class="barista-order-card"><p>Clocked in: ${escapeHtml(new Date(a.clocked_in_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'}))}</p><h1 id="workerElapsed"></h1><button id="clockOut">Clock Out</button></section></div>`;
 document.getElementById('clockOut').onclick=()=>{mode='out';render();};document.getElementById('chooseWorker').onclick=()=>{selected='';mode='in';render();};timer();return;
 }
 host.innerHTML=`<form id="workerClockForm" class="clock-panes"><section class="barista-order-card"><h3>${mode==='out'?'Confirm Clock Out':'Clock In'}</h3><label>Username<select name="username" required><option value="">Select active worker</option>${workers.map(w=>`<option value="${escapeHtml(w.username)}" ${selected===w.username?'selected':''}>${escapeHtml(w.username)} · ${escapeHtml(w.name)}</option>`).join('')}</select></label><label>Drink PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="off" required></label><p data-clock-error role="alert"></p><button type="submit">${mode==='out'?'Clock Out':'Clock In'}</button>${mode==='out'?'<button type="button" id="cancelClockOut">Keep working</button>':''}</section><section class="barista-order-card"><div class="count-keypad">${['1','2','3','4','5','6','7','8','9','Clear','0','⌫'].map(n=>`<button type="button" data-clock-key="${n}">${n}</button>`).join('')}</div></section></form>`;
 const form=document.getElementById('workerClockForm');form.elements.username.onchange=()=>{selected=form.elements.username.value;mode='in';render();};document.getElementById('cancelClockOut')?.addEventListener('click',()=>{mode='in';render();});
 for(const button of form.querySelectorAll('[data-clock-key]'))button.onclick=()=>{const input=form.elements.pin,key=button.dataset.clockKey;input.value=key==='Clear'?'':key==='⌫'?input.value.slice(0,-1):input.value.length<6?input.value+key:input.value;};
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;form.querySelector('button[type=submit]').disabled=true;const action=mode;
 try{const result=await KBRCloud.rpc('kbr_clock_worker',{p_username:form.elements.username.value,p_pin:form.elements.pin.value,p_action:action});form.elements.pin.value='';if(result.error)throw Error(result.error);selected=result.profile.username;mode='in';try{localStorage.setItem('kbr_clock_profile_v1',JSON.stringify(result.profile));}catch{}await refresh(true);status.textContent=action==='out'?'Clocked out.':'Clocked in. Your name will appear in Barista Drinks if today’s drink has not been redeemed.';}
 catch(error){const errorEl=document.querySelector('[data-clock-error]');if(errorEl)errorEl.textContent=error.message;else status.textContent=error.message;const button=document.querySelector('button[type=submit]');if(button)button.disabled=false;}finally{busy=false;}
 };
}
async function refresh(force=false){if(refreshing)return;refreshing=true;try{const rows=await KBRCloud.rows('/rest/v1/kbr_worker_attendance?clocked_out_at=is.null&select=*&order=clocked_in_at.desc');const signature=JSON.stringify(rows);attendance=rows;if(force||signature!==last){last=signature;if(force||!document.getElementById('workerClockForm')?.elements.pin.value)render();}timer();KBRCloud.status('Connected · attendance updates every 5 sec');}catch(error){KBRCloud.status('Attendance connection unavailable',true);throw error;}finally{refreshing=false;}}
async function start(){if(!KBRCloud.requireLogin())return;try{if(!['owner','operator'].includes(await KBRCloud.role()))throw Error('Staff login required.');workers=await KBRCloud.rpc('kbr_clock_roster',{});await refresh(true);setInterval(()=>{if(!document.hidden&&!busy)refresh().catch(error=>status.textContent=error.message);},5000);setInterval(timer,1000);}catch(error){host.textContent='Unable to load worker clock: '+error.message;const button=document.createElement('button');button.textContent='Retry';button.onclick=start;host.append(button);}}start();
})();
